[package]
name = "chron-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
dashmap = "5.4.0"
futures = "0.3.25"
serde_json = { version = "1.0.91", features = ["raw_value"] }
siphasher = "0.3.10"
sqlx = { version = "0.6.2", features = ["json", "postgres", "time", "uuid", "runtime-tokio-native-tls", "sqlite"] }
time = { version = "0.3.17", features = ["serde", "formatting"] }
tokio = { version = "1.24.1", features = ["full"] }
uuid = { version = "1.2.2", features = ["v4", "serde"] }
chron-base = { path = "../chron-base" }
sea-query = { version = "0.28.2", features = ["backend-postgres", "with-time", "with-uuid", "derive", "attr"] }
serde = { version = "1.0.152", features = ["derive"] }
sea-query-binder = { version = "0.3.0", features = ["sqlx", "sqlx-postgres", "with-time", "with-uuid"] }
tracing = { version = "0.1.37", features = ["log"] }
log = "0.4.17"
base64 = "0.21.0"
